name: docker-publish

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: setup-buildx
        uses: docker/setup-buildx-action@v2
      - name: auth
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/aelindeman/plex-webhook-newrelic:latest,ghcr.io/aelindeman/plex-webhook-newrelic:${{ github.ref_name }}
